version: '3.8'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads

  db:
    image: postgres:13
    container_name: ${DATABASE_HOST:-postgres-db}
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
